######################################################################
# Automatically generated by qmake (3.0) Tue Mar 22 15:59:45 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = testPkgInfo
INCLUDEPATH += .

# Input
HEADERS += ../pkginfo.h
SOURCES += testpkginfo.cpp ../pkginfo.cpp
