######################################################################
# Automatically generated by qmake (3.0) Tue Mar 22 15:54:03 2016
######################################################################

TEMPLATE = app
TARGET = qkgr
INCLUDEPATH += .

# Input
HEADERS += pkginfo.h pkgr.h ui_main.h
FORMS += main.ui
SOURCES += main.cpp pkginfo.cpp pkgr.cpp

QT += widgets

CONFIG += c++11
